Products
Gr1ngoire/From-hungry-land pull request #2
Opened 2023-02-02 23:09 UTC by HoolyDuck

---
Discuss about controllers, db data source and general code

2023-02-02 23:12 UTC, HoolyDuck commented
I will move route strings to enums after this is resolved !

2023-02-03 18:45 UTC, Gr1ngoire requested changes

2023-02-03 18:45 UTC, Gr1ngoire commented on server/src/db/migrations/1675371798079-init.ts
> +        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "nickname" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAIN
As I asked, you need to remove this

2023-02-03 18:45 UTC, Gr1ngoire commented on server/src/db/migrations/1675371798079-init.ts
> +        await queryRunner.query(`DROP TABLE "role"`);
And remove this

2023-02-03 18:45 UTC, HoolyDuck commented on server/src/db/migrations/1675371798079-init.ts
> +        await queryRunner.query(`DROP TABLE "role"`);
ой

2023-02-03 19:03 UTC, Gr1ngoire approved these changes

2023-02-03 19:03 UTC, merged