Recipes
Gr1ngoire/From-hungry-land pull request #3
Opened 2023-02-03 16:11 UTC by tonujet

Provide basic recipe logic

2023-02-03 16:12 UTC, HoolyDuck commented
фіга комітів

2023-02-04 09:40 UTC, Gr1ngoire requested changes

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/common/exceptions/entity/entity-not-found.exception.ts
> +    constructor(message: string, id: number, status?: number) {
Why we need id here?

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/common/types/types.ts
> +export {RecipeQueryOptionType} from "./recipe.query.option/recipe.query.option.type"
this import should look like ./recipe/recipe (look at example like DbClient)

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/controllers/product/product.controller.ts
> +      res.json(await productService.getAll())
productService should be injected, take it back everuwhere it was removed

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/controllers/product/product.controller.ts
> +      res.json(products);
Also, when we send response, there should be specified status (in every controller response)

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/db/entities/recipe.entity.ts
> +import {DbTablesNamesEnum, RecipeDifficulty} from "../../common/enums/enums";
import should be '@/common/enums/enums'

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/db/entities/role.entity.ts
> +import {DbTablesNamesEnum} from "../../common/enums/enums";
import

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/db/entities/user.entity.ts
> +import {DbTablesNamesEnum} from "../../common/enums/enums";
import

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/db/migrations/1675360350104-roles_table.ts
> +        await queryRunner.query(`DROP TABLE "roles"`);
We can not change tables names in migrations because we won't be able to roll back
Take it back as it was, I will handle that

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/db/migrations/1675365819475-users_table.ts
> +        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone`);
Same here, set previous role table name back

2023-02-04 09:40 UTC, Gr1ngoire commented on server/src/repositories/product/product.repository.ts
> -import { Product } from "../../db/entities/product.entity";
Take it back

2023-02-04 11:37 UTC, Gr1ngoire approved these changes

2023-02-04 11:39 UTC, merged